# Application URL
url=https://www.omrbranch.com/

# Browser Configuration CHROME/FIREFOX/EDGE
browser=chrome

# Cucumber JSON Report Path
jsonPath=/target/cucumber.json

# JVM Report Output Folder
jvmReportPath=/target